pipeline:

  test-and-build:
    image: golang
    commands:
      - make
    when:
      event: [push, tag]
      branch: [master, develop, refs/tags/*]
      
  github_release:
    image: plugins/github-release
    secrets: [ github_release_api_key ] 
    files:
      - build/bin/kusd
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
