pipeline:

  test-and-build:
    image: deis/go-dev
    commands:
      - printenv
14
      - build/bin/geth
15
    checksum:
16
      - md5
17
      - sha1
18
      - sha256
19
      - sha512
20
      - adler32
21
      - crc32
22
    when:
23
      event: tag
24

      - make
    when:
      event: [push, tag]
      branch: [master, develop, refs/tags/*]
      
  github_release:
    image: plugins/github-release
    files:
      - build/bin/geth
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
