pipeline:

  test-and-build:
    image: deis/go-dev
    commands:
      - make
    when:
      branch: [master, develop]
      
  github_release:
    image: plugins/github-release
    files:
      - build/bin/geth
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
