pipeline:

  test-and-build:
    image: deis/go-dev
    commands:
      - make
    when:
      event: [push, tag]
      branch: [master, develop, refs/tags/*]
      
  github_release:
    image: plugins/github-release
    files:
      - build/bin/geth
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    api_key: ${GITHUB_RELEASE_API_KEY}
    when:
      event: tag
