pipeline:

  test-and-build:
    image: golang
    secrets: [ GITHUB_RELEASE_API_KEY ] 
    commands:
      - echo $GITHUB_RELEASE_API_KEY
      - echo $${GITHUB_RELEASE_API_KEY}
      - make
    when:
      event: [push, tag]
      branch: [master, develop, refs/tags/*]
      
  github_release:
    image: plugins/github-release
    files:
      - build/bin/geth
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
