version: '3'

services:
  kowala-app-web:
    image: kowala-app-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ../:/kcoin:delegated
    entrypoint: "tail -f /dev/null"
